### PR TITLE
[herd] Rename the regression test directories

### PR DESCRIPTION
**Pull request by eth-arm**
This PR moves the existing Herd regression tests to a more informative location.

"Unit tests" test code from _inside_ an API boundary, e.g. [confirming that reading a file works correctly](https://github.com/herd/herdtools7/blob/9677690cbd854a8fbbbe19d97eafda5a3ca95821/internal/lib/tests/filesystem_test.ml). "End-to-end tests" test code from _outside_ an API boundary, e.g. confirming that a complete binary produces expected output for given input. Our API boundary is the binaries `herd7`, `litmus7`, etc. These tests test the `herd7` binary as a whole, and are thus not unit tests, and so I am renaming them accordingly.

The new layout should also be able to be more informative and more flexible for future kinds of tests. The new layout is:

```
$GIT_DIR/herd/tests/
    instructions/
        AArch64/
        PPC/
    diycross/
        AArch64/
    some-future-test-kind/
        AArch64/
```

### CODE REVIEW

**Comment by jalglave** [comment]
hi Ethel, sorry it looks like this PR now has conflicts (after I merged your "Regression tests" PR). 
Please could you look into this?
Thanks,
Jade

**Comment by eth-arm** [comment]
I've moved the success message changes to PR #104.

**Comment by eth-arm** [comment]
This should be ready to merge.

**Comment by eth-arm** [comment]
I have brought this back up to date with `master`.

**Pull request merged**
