### PR TITLE
[gen] Generate simple loads and stores on pairs

### PR DESCRIPTION
**Pull request by maranget**
The `Pa` pseudo-relaxation commands a pair access; `PaN` is for non-temporal accesses; and `PaI` is for "ordered" pair accesses (_i.e._ `STILP` and `LDIAPP` instructions).

The pair annotations `Pa` and `PaI` also apply to the "exclusive pair" edge `LxSx`.

### CODE REVIEW

**Comment by maranget** [comment]
Hi @jalglave, this PR includes a modification of the cat model (commit 9fcc12d66c4c2e3a96f0bf4eec6647b1a6dc1c3a), Namely the two (?) memory effacts performed by the  instructions `STILP` and `LDIAPP` follow some ordering constraints.
>  `LDIAPP <Wt1>, <Wt2>, [<Xn|SP>]`... The Memory effects associated with Xt1/Wt1 are Ordered-before the Memory effects associated with Xt2/Wt2.

> `STILP <Wt1>, <Wt2>, [<Xn|SP>]`... When using the pre-index addressing mode, the Memory effects associated with Xt2/Wt2 are Ordered-before
the Memory effects associated with Xt1/Wt1.


Tests [L082](https://github.com/herd/herdtools7/blob/62829728a1504d7f2b65cf16469a2ef9de8dcec2/herd/tests/instructions/AArch64/L082.litmus), [L083](https://github.com/herd/herdtools7/blob/62829728a1504d7f2b65cf16469a2ef9de8dcec2/herd/tests/instructions/AArch64/L083.litmus) and [L084](https://github.com/herd/herdtools7/blob/62829728a1504d7f2b65cf16469a2ef9de8dcec2/herd/tests/instructions/AArch64/L084.litmus)  check for these constraints.

**Comment by relokin** [comment]
Hi @maranget, @jalglave and I had a look and we think we should rename `iico_order` to `asl_po`. Otherwise is there something blocking this? How can I help to get this merged?

**Comment by hugookeeffe** [comment]
I have looked through the gen code and tried generating with diyone7, and everything seems good to me. 
I was able to generate tests with this patch and they seem correct.
I haven't come across anything that didn't work. Thanks for the patch!

**Comment by maranget** [comment]
Hi @hugookeeffe, would you please share your config file? THis would be very helpful. Thanks.

**Comment by hugookeeffe** [comment]
no problem @maranget, here it is:
```

-arch AArch64

-nprocs 2
-eprocs

-size 6

-relax PaN
-safe Rfe Fre Coe Hat DpAddrdR DpAddrdW DpAddrsR DpAddrsW DpDatadW DpDatasW DpCtrldW DpCtrlsW DpCtrlIsbdR [DpAddrdR, ISBd*R] [DpAddrdW, ISBd*R] DpCtrlIsbsR [DpAddrsR, ISBs*R] [DpAddrsW, ISBs*R] [DpAddrsR, ISBd*R] [DpAddrsW, ISBd*R] [DpAddrdR, ISBs*R] [DpAddrdW, ISBs*R] [DpAddrdR, Pod*W] [DpAddrdW, Pod*W] [DpAddrsR, Pos*W] [DpAddrsW, Pos*W] [DpAddrsR, Pod*W] [DpAddrsW, Pod*W] [DpAddrdR, Pos*W] [DpAddrdW, Pos*W] [DpAddrdW, Rfi] [DpDatadW, Rfi] [DpAddrsW, Rfi] [DpDatasW, Rfi] DMB.SYd** DMB.SYs** PodWRLA PosWRLA DMB.LDdR* DMB.LDsR* PodR*AP PodR*QP PosR*AP PosR*QP PodRRAA PodRRQA PosRRAA PosRRQA PodRRAQ PodRRQQ PosRRAQ PosRRQQ PodRWAL PodRWQL PosRWAL PosRWQL DMB.STdWW DMB.STsWW Pod*WPL Pos*WPL PodWWLL PosWWLL Pos*W LxSx LxSxAP LxSxPL LxSxAL [LxSx, RfiPA] [LxSx, RfiPQ] [LxSxAP, RfiPA] [LxSxAP, RfiPQ] [LxSxPL, RfiLA] [LxSxPL, RfiLQ] [LxSxAL, RfiLA] [LxSxAL, RfiLQ] Amo.Swp Amo.Cas Amo.LdAdd Amo.LdEor Amo.LdClr Amo.LdSet Amo.StAdd Amo.StEor Amo.StClr Amo.StSet Amo.SwpAP Amo.CasAP Amo.LdAddAP Amo.LdEorAP Amo.LdClrAP Amo.LdSetAP Amo.SwpPL Amo.CasPL Amo.LdAddPL Amo.LdEorPL Amo.LdClrPL Amo.LdSetPL Amo.StAddPL Amo.StEorPL Amo.StClrPL Amo.StSetPL Amo.SwpAL Amo.CasAL Amo.LdAddAL Amo.LdEorAL Amo.LdClrAL Amo.LdSetAL [Amo.Swp, RfiPA] [Amo.Cas, RfiPA] [Amo.LdAdd, RfiPA] [Amo.LdEor, RfiPA] [Amo.LdClr, RfiPA] [Amo.LdSet, RfiPA] [Amo.StAdd, RfiPA] [Amo.StEor, RfiPA] [Amo.StClr, RfiPA] [Amo.StSet, RfiPA] [Amo.Swp, RfiPQ] [Amo.Cas, RfiPQ] [Amo.LdAdd, RfiPQ] [Amo.LdEor, RfiPQ] [Amo.LdClr, RfiPQ] [Amo.LdSet, RfiPQ] [Amo.StAdd, RfiPQ] [Amo.StEor, RfiPQ] [Amo.StClr, RfiPQ] [Amo.StSet, RfiPQ] [Amo.SwpAP, RfiPA] [Amo.CasAP, RfiPA] [Amo.LdAddAP, RfiPA] [Amo.LdEorAP, RfiPA] [Amo.LdClrAP, RfiPA] [Amo.LdSetAP, RfiPA] [Amo.SwpAP, RfiPQ] [Amo.CasAP, RfiPQ] [Amo.LdAddAP, RfiPQ] [Amo.LdEorAP, RfiPQ] [Amo.LdClrAP, RfiPQ] [Amo.LdSetAP, RfiPQ] [Amo.SwpPL, RfiLA] [Amo.CasPL, RfiLA] [Amo.LdAddPL, RfiLA] [Amo.LdEorPL, RfiLA] [Amo.LdClrPL, RfiLA] [Amo.LdSetPL, RfiLA] [Amo.StAddPL, RfiLA] [Amo.StEorPL, RfiLA] [Amo.StClrPL, RfiLA] [Amo.StSetPL, RfiLA] [Amo.SwpPL, RfiLQ] [Amo.CasPL, RfiLQ] [Amo.LdAddPL, RfiLQ] [Amo.LdEorPL, RfiLQ] [Amo.LdClrPL, RfiLQ] [Amo.LdSetPL, RfiLQ] [Amo.StAddPL, RfiLQ] [Amo.StEorPL, RfiLQ] [Amo.StClrPL, RfiLQ] [Amo.StSetPL, RfiLQ] [Amo.SwpAL, RfiLA] [Amo.CasAL, RfiLA] [Amo.LdAddAL, RfiLA] [Amo.LdEorAL, RfiLA] [Amo.LdClrAL, RfiLA] [Amo.LdSetAL, RfiLA] [Amo.SwpAL, RfiLQ] [Amo.CasAL, RfiLQ] [Amo.LdAddAL, RfiLQ] [Amo.LdEorAL, RfiLQ] [Amo.LdClrAL, RfiLQ] [Amo.LdSetAL, RfiLQ] [Pod**, Amo.SwpAL] [Pod**, Amo.CasAL] [Pod**, Amo.LdAddAL] [Pod**, Amo.LdEorAL] [Pod**, Amo.LdClrAL] [Pod**, Amo.LdSetAL] [Pos**, Amo.SwpAL] [Pos**, Amo.CasAL] [Pos**, Amo.LdAddAL] [Pos**, Amo.LdEorAL] [Pos**, Amo.LdClrAL] [Pos**, Amo.LdSetAL] [Amo.SwpAL, Pod**] [Amo.CasAL, Pod**] [Amo.LdAddAL, Pod**] [Amo.LdEorAL, Pod**] [Amo.LdClrAL, Pod**] [Amo.LdSetAL, Pod**] [Amo.SwpAL, Pos**] [Amo.CasAL, Pos**] [Amo.LdAddAL, Pos**] [Amo.LdEorAL, Pos**] [Amo.LdClrAL, Pos**] [Amo.LdSetAL, Pos**] [Pod**, Amo.SwpAL, Pod**] [Pod**, Amo.CasAL, Pod**] [Pod**, Amo.LdAddAL, Pod**] [Pod**, Amo.LdEorAL, Pod**] [Pod**, Amo.LdClrAL, Pod**] [Pod**, Amo.LdSetAL, Pod**] [Pos**, Amo.SwpAL, Pos**] [Pos**, Amo.CasAL, Pos**] [Pos**, Amo.LdAddAL, Pos**] [Pos**, Amo.LdEorAL, Pos**] [Pos**, Amo.LdClrAL, Pos**] [Pos**, Amo.LdSetAL, Pos**]

```
I will also email you the file, as GitHub isn't allowing me to link a .conf file

**Comment by hugookeeffe** [comment]
thank you for the quick fix @maranget !

**Comment by maranget** [comment]
Hi @relokin. One difficulty remains : this PR includes a small model change (commit https://github.com/herd/herdtools7/commit/9fcc12d66c4c2e3a96f0bf4eec6647b1a6dc1c3a).

**Comment by relokin** [comment]
> Hi @relokin. One difficulty remains : this PR includes a small model change (commit [9fcc12d](https://github.com/herd/herdtools7/commit/9fcc12d66c4c2e3a96f0bf4eec6647b1a6dc1c3a)).

I think the cat file change is fine. @jalglave do we still want to rename `iico_order` to `asl-po` or should we leave it as-is?

**Comment by maranget** [comment]
Just rebased.

**Comment by jalglave** [comment]
> > Hi @relokin. One difficulty remains : this PR includes a small model change (commit [9fcc12d](https://github.com/herd/herdtools7/commit/9fcc12d66c4c2e3a96f0bf4eec6647b1a6dc1c3a)).
> 
> I think the cat file change is fine. @jalglave do we still want to rename `iico_order` to `asl-po` or should we leave it as-is?

hi @relokin @maranget the MMRB ratified the use of iico_order here so the model changes are fine by me.
Thanks,
Jade

**Pull request merged**
