### PR TITLE
[asl] New public name "aslref" for the aslseq tool.

### PR DESCRIPTION
**Pull request by maranget**
The tool aslseq is now installed as "aslref". That way, changes are minimal.

### CODE REVIEW

**Comment by jalglave** [comment]
Thank you. Please let's merge.
Jade

**Comment by HadrienRenaud** [comment]
Hi @maranget 

FYI this breaks the asllib tests...
The `aslseq` util that some tests are dependant on is not available and so they fetch the one installed on the system. You can check that by comparing the output of `dune exec aslref -- --version`, `dune exec aslseq -- --version` and writing `  $ aslseq --version; aslref --version` in `asllib/tests/asl.t/run.t`

**Comment by maranget** [comment]
Sorry for this.

**Comment by HadrienRenaud** [comment]
See #662

**Pull request merged**
