### PR TITLE
[herd] Define the si relation for FAULT events

### PR DESCRIPTION
**Pull request by relokin**
Signed-off-by: Nikos Nikoleris <nikos.nikoleris@arm.com>

### CODE REVIEW

**Comment by maranget** [comment]
Hi @nikos, I am checking this PR against regression on the KVM base. When done I'll merge this PR into master.

**Comment by relokin** [comment]
Thanks @lukeg101

**Comment by maranget** [comment]
Merged thanks, It would be convenient for me if you could rebase your PR #451 on the new master

**Comment by relokin** [comment]
Thanks! I'll rebase #452 right away.

**Pull request merged**
