### PR TITLE
[all]: AArch64 Added LDRB/H and STRB/H shifters

### PR DESCRIPTION
**Pull request by lukeg101**
This patch adds support for inline barrel shifters
for LDRB/H and STRB/H barrel shifters for all tools
that use these instructions.

tests provided.

### CODE REVIEW

**Comment by maranget** [comment]
LGTM, except one important issue that originates in a long standing shortcoming  that we are going to solve now, thanks to your initiative.

herdtools accept the illegal addressing mode `[Xn,Wm]` (register indexed with 32bit register, no extension). As this mode is rejected by the assembler, litmus prints this mode as `[Xn,Wm,SXTW]`. For consistency, (!) herd does the same when printing the illegal addressing mode. Then, everything works fine: the assembler is happy, `diy` generates the correct syntax, and herd accepts the incorrect syntax (without extension) as implicitly specifying signed extension.

Let clean the dust under the carpet:
 + The parser should reject the incorrect syntax
  + diy generator should emit the signed extension

I'll suggest some patches, but more probably has to be done. For instance some `assert false` will have to be added in some places, instead of performing the silent replacement of no extension by sxtw.

**Comment by maranget** [comment]
And here is a patch for rejecting `[Xn,Wm]` at parse time. This is a minimal patch that does not attempt to solve all untimely parsing of illegal constructions... As I am quite sure that there are others.
[B.patch.txt](https://github.com/herd/herdtools7/files/8920534/B.patch.txt)

**Comment by lukeg101** [comment]
Hi Luc, thanks for taking a look at this! Is there anything I can do to help?

**Comment by lukeg101** [comment]
Hi Luc, I'm doing this now. Do you have advice for wording of the commit for the patches you provided?
I have merged A and B into one patch and rebased it onto the original PR (I will push after I have added tests)

**Comment by maranget** [comment]
> Hi Luc, I'm doing this now. Do you have advice for wording of the commit for the patches you provided?
> I have merged A and B into one patch and rebased it onto the original PR (I will push after I have added tests)

What about `[gen] command sign extension when generating "W" register indexed accesses` and `[all] reject "W" register indexed accesses at parsing` ? (English mistakes fixed, if any)

**Comment by maranget** [comment]
Merged, thanks for your work and initiative.

**Pull request merged**
