### PR TITLE
[AArch64] Initial formalisation of Ifetch

### PR DESCRIPTION
**Pull request by artkhyzha**
This release presents a number of changes, listed below. Those changes should be reflected in the next issue of the Arm ARM. For more details please contact [memory-model@arm.com](mailto:memory-model@arm.com).

This version of the model introduces a number of concepts required to describe orderings due to instruction fetch. Most notable are the notions of Instr-read-ordered-before, IC-ordered-before, and IC-Coherence-after.

This is organised in two distinct commits:
1. a reorganisation of the pre-existing VMSA model with no semantics change;
2. an extension of that reorganised VMSA model with definitions and constraints pertaining to instruction fetch.

### CODE REVIEW

**Comment by jalglave** [comment]
Thanks @artkhyzha - I've looked at both commits and they look good.
@maranget please could you regress each commit?
If they regress fine, please do *not* squash them before merging: we'd like to keep two commits here.
Thanks in advance,
Jade

**Comment by maranget** [comment]
Hi @artkhyzha, there was a conflict with master, due to the recent introduction of the `aarch32.cat` model. I have resolved the conflict and modified `aarch32.cat` in some added commit, so that `aarch32.cat` is compatible with the new `aarch64.cat` model.

Regression (`make test`) is fine after each of the three commits.

**Comment by maranget** [comment]
VMSA, non-mixed and mixed size regressions are fine.

**Comment by jalglave** [comment]
> VMSA, non-mixed and mixed size regressions are fine. Should I merge?

yes please @maranget!
thanks,
Jade

**Comment by maranget** [comment]
Merged, thanks to all!

**Pull request merged**
