### PR TITLE
Add support for fault types in litmus test

### PR DESCRIPTION
**Pull request by relokin**

### CODE REVIEW

**Comment by maranget** [comment]
Hi @relokin, regression tests by themselves are not a problem. The actual difficulties are more in coping with old litmus logs... It is very important that tools, and in particular `mcompare7` do not get confused by the new format.

**Comment by relokin** [comment]
> Hi @relokin, regression tests by themselves are not a problem. The actual difficulties are more in coping with old litmus logs... It is very important that tools, and in particular `mcompare7` do not get confused by the new format.

Thanks @luc, I will make sure that `mcompare7` has a backward compatible behavior. If there is any other tool we need to think carefully about please let me know.

**Comment by maranget** [comment]
You may have a look at `msum7` too.  It may be of a concern that a completely backward compatible behaviour would make the new feature invisible... I mean if the "backward compatible"  means that the fault type is ignored by `mcompare7` and 'msum7`. I have not thought a lot about this though.
'

**Comment by maranget** [comment]
At the moment `mcompare7` seems to ignore the fault type from fault occurrences in logs. As a result `mcompare7` finds most test outcomes not to regress. The is one exception:
```
AArch64 I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR
{
pte_x=(oa:phy_x,valid:0,db:0);

0:X1=pte_x;

0:X0=(oa:phy_x,valid:1,db:0);
0:X2=(oa:phy_x,valid:1,db:1);
0:X3=y;

1:X3=y;
1:X1=x;
}
P0             | P1           ;
 STR X0,[X1]   | LDR W9,[X3]  ;
 DSB ISH       | DSB ISH      ;
 STR X2,[X1]   | ISB          ;
 DSB ISH       |L1:           ;
 MOV W9,#1     | STR W9,[X1]  ;
 STR W9,[X3]   |              ;
exists(1:X9=1 /\ fault(P1:L1,x))
```
Here is mcompare7 output, when applied to to old and new log file:
```
Diffs*
                                |Kind | VA.600                    VA.31oct.600             
-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR|Allow| [1:X9=0; ~fault(P1:L1,x)] +[1:X9=0; fault(P1:L1,x)]
                                |Ok   | [1:X9=0; fault(P1:L1,x)]                           
                                |     | [1:X9=1; ~fault(P1:L1,x)]                          
                                |     | [1:X9=1; fault(P1:L1,x)]    

```
This disturbing result originates in having two different `Fault(P1:L1,x)` faults in the new log:
```
% herd7 -conf VA.cfg tests/I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR.litmus 
Test I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR Allowed
States 5
1:X9=0;  ~Fault(P1:L1,x);
1:X9=0; Fault(P1:L1,x,MMU:Permission);
1:X9=0; Fault(P1:L1,x,MMU:Translation);
1:X9=1;  ~Fault(P1:L1,x);
1:X9=1; Fault(P1:L1,x,MMU:Permission);
Ok
Witnesses
Positive: 1 Negative: 4
Flag Assuming-common-inner-shareable-domain
Condition exists (1:X9=1 /\ fault(P1:L1,x))
Observation I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR Sometimes 1 4
Time I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR 0.06
Hash=29849d4f49d31c2e724ee07b00cd704d


```

**Comment by maranget** [comment]
Hum the new feature has the following puzzling consequence. Let us run the new herd7 on test **I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR**:
```
Test I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR Allowed
States 5
1:X9=0;  ~Fault(P1:L1,x);
1:X9=0; Fault(P1:L1,x,MMU:Permission);
1:X9=0; Fault(P1:L1,x,MMU:Translation);
1:X9=1;  ~Fault(P1:L1,x);
1:X9=1; Fault(P1:L1,x,MMU:Permission);
Ok
Witnesses
Positive: 1 Negative: 4
Flag Assuming-common-inner-shareable-domain
Condition exists (1:X9=1 /\ fault(P1:L1,x))
Observation I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR Sometimes 1 4
Time I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR 0.06
Hash=29849d4f49d31c2e724ee07b00cd704d
```
Now let us change the test slightly, changing the final condition into ` exists 1:X9=1 /\ fault(P1:L1,x,MMU:Translation)`, we have:
```
Test I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR Allowed
States 3
1:X9=0;  ~Fault(P1:L1,x,MMU:Translation);
1:X9=0; Fault(P1:L1,x,MMU:Translation);
1:X9=1;  ~Fault(P1:L1,x,MMU:Translation);
No
Witnesses
Positive: 0 Negative: 5
Flag Assuming-common-inner-shareable-domain
Condition exists (1:X9=1 /\ fault(P1:L1,x,MMU:Translation))
Observation I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR Never 0 5
Time I2V-DSB-WEXP-DSB+obs+DSB-ISH-STR 0.04
Hash=29849d4f49d31c2e724ee07b00cd704d
```
Wouldn't it  be better to have all faults displayed, regardless of their type? And also to forget about types in "fault not present atom" `~Fault(P1:L1,x)`?

**Comment by maranget** [comment]
Thanks, I'll update the interface.

**Comment by relokin** [comment]
@maranget , now rebased on top of master.

**Comment by maranget** [comment]
I do not believe it. Github noticed the merge!

**Pull request merged**
