### PR TITLE
[all]: Add Mips instructions

### PR DESCRIPTION
**Pull request by lukeg101**
Motivation: We wish to test compilation targeting the MIPS architecture.

To do so we need to support many new instructions. 
This patch adds support for the following which pass in herd and litmus (under qemu mips64 emulation):
- testing for MIPS
- Lui instruction
- parsing non$ registers
- NOP instruction
- DADDU / DADDIU instruction
- LD instruction
- JR instruction
- a4-a7 registers (under O64 ABI)
- dext instruction
- dsll instruction
- move instruction
- a mips64-qemu litmus profile
- mips instruction.h in litmus

Tests are provided - they pass in herd, and under litmus (using qemu for mips64 emulation), results:
```
Mon Aug 21 05:16:19 PM BST 2023
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A000.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A000

{
}
 P0         ;
 move $2,$3 ;

forall (0:$2=0)
Generated assembler
#START _litmus_P0
	move $3,$8
Test A000 Required
Histogram (1 states)
2000000:>0:$2=0;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$2=0) is validated
Hash=1adc8fedc9a06151f8c5f9ace89ae992
Observation A000 Always 2000000 0
Time A000 0.27
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A001.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A001

{
}
 P0       ;
 lui $4,1 ;

forall (0:$4=65536)
Generated assembler
#START _litmus_P0
	lui $3,1
Test A001 Required
Histogram (1 states)
2000000:>0:$4=65536;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$4=65536) is validated
Hash=0b5207526f2604aed1ba910c050cf274
Observation A001 Always 2000000 0
Time A001 0.27
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A002.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A002

{
 0:$0=0; 0:$1=0; 0:$2=0; 0:$3=0; 0:$4=0; 0:$5=0; 0:$6=0; 0:$7=0; 0:$8=0; 0:$9=0; 0:$10=0; 0:$11=0; 0:$12=0; 0:$13=0; 0:$14=0; 0:$15=0; 0:$16=0; 0:$17=0; 0:$18=0; 0:$19=0; 0:$20=0; 0:$21=0; 0:$22=0; 0:$23=0; 0:$24=0; 0:$25=0; 0:$26=0; 0:$27=0; 0:$28=0; 0:$29=0; 0:$30=0; 0:$31=0; 0:$a4=0; 0:$a5=0; 0:$a6=0; 0:$a7=0;
}
 P0         ;
 move $2,$3 ;
 move $2,$3 ;

forall (0:$2=0)
Generated assembler
#START _litmus_P0
	move $3,$8
	move $3,$8
Test A002 Required
Histogram (1 states)
2000000:>0:$2=0;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$2=0) is validated
Hash=eeb5d27692ab3f5a8ae4598467d43a23
Observation A002 Always 2000000 0
Time A002 0.29
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A003.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A003

{
}
 P0  ;
 nop ;

forall (0:$4=0)
Generated assembler
#START _litmus_P0
	nop
Test A003 Required
Histogram (1 states)
2000000:>0:$4=0;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$4=0) is validated
Hash=7dbd8e4fdafc2b299a8e4b02a379dcaa
Observation A003 Always 2000000 0
Time A003 0.26
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A004.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A004

{
}
 P0             ;
 daddu $2,$3,$4 ;
 daddiu $2,$3,2 ;

forall (0:$2=2 /\ 0:$3=0)
Generated assembler
#START _litmus_P0
	daddu $8,$2,$7
	daddiu $8,$2,2
Test A004 Required
Histogram (1 states)
2000000:>0:$2=2; 0:$3=0;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$2=2 /\ 0:$3=0) is validated
Hash=d1f2e271118554bb2668dea9cf458795
Observation A004 Always 2000000 0
Time A004 0.28
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A005.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A005

{
 int64_t x=1;
 int64_t 0:$5=x;
}
 P0          ;
 ld $4,0($5) ;

forall (0:$4=1)
Generated assembler
#START _litmus_P0
	ld $3,0($2)
Test A005 Required
Histogram (1 states)
2000000:>0:$4=1;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$4=1) is validated
Hash=d33fef1633282273cf65bd2cad3b64fb
Observation A005 Always 2000000 0
Time A005 0.41
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A006.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A006

{
 0:$4=0:L1; 0:$6=2; 0:$5=0;
}
 P0         ;
 b L2       ;
 nop        ;
 move $5,$6 ;
 L2: jr $4  ;
 nop        ;
 L1: nop    ;

forall (0:$5=0)
Generated assembler
#START _litmus_P0
	nop
	b 0f
	nop
	move $2,$3
0:
	jr $4
	nop
1:
	nop
Test A006 Required
Histogram (1 states)
2000000:>0:$5=0;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$5=0) is validated
Hash=9cc430355a613356b27b40abfd69450d
Observation A006 Always 2000000 0
Time A006 0.40
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A007.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A007

{
 0:$4=65536;
}
 P0              ;
 dext $5,$4,16,1 ;

forall (0:$5=1)
Generated assembler
#START _litmus_P0
	DEXT $3,$9,16,1
Test A007 Required
Histogram (1 states)
2000000:>0:$5=1;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$5=1) is validated
Hash=728146fd0b742578e9c74d0619cb9fdd
Observation A007 Always 2000000 0
Time A007 0.28
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for herd/tests/instructions/MIPS/A008.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MIPS A008

{
 0:$5=1;
}
 P0           ;
 dsll $4,$5,1 ;

forall (0:$4=2)
Generated assembler
#START _litmus_P0
	dsll $3,$6,1
Test A008 Required
Histogram (1 states)
2000000:>0:$4=2;
Ok

Witnesses
Positive: 2000000, Negative: 0
Condition forall (0:$4=2) is validated
Hash=aaf6db304595e21f10c724bd8f6e849b
Observation A008 Always 2000000 0
Time A008 0.29
Revision 186f8fd6682ec1908dc10207c0b6e47aa06133aa, version 7.56+03
Command line: ./_build/install/default/bin/litmus7 -mach litmus/libdir/mips64-qemu.cfg -set-libdir litmus/libdir -o out herd/tests/instructions/MIPS/@all
Parameters
#define SIZE_OF_TEST 5000
#define NUMBER_OF_RUN 200
#define AVAIL 2
#define STRIDE 1
#define MAX_LOOP 0
/* gcc options: -Wall -std=gnu99 -O2 -pthread */
/* gcc link options: -static */
/* barrier: user */
/* launch: changing */
/* affinity: none */
/* memory: direct */
/* stride: 1 */
/* safer: write */
/* preload: random */
/* speedcheck: no */
/* alloc: dynamic */
/* proc used: 2 */
GCC=mips64-linux-gnuabi64-gcc
LITMUSOPTS=
Mon Aug 21 05:16:23 PM BST 2023
```

### CODE REVIEW

**Comment by lukeg101** [comment]
Looking at this PR - the herd semantics already match the architectural intent (under QEMU), so I do not need to guard on telechat here @maranget

**Comment by lukeg101** [comment]
Hi Luc, I added a patch to support indirect branches for the telechat experiments. Also fixed a parsing issue with $ registers and rebased onto master. This is ready now

**Comment by maranget** [comment]
Hi @lukeg101. I have reviewed this PR. It's ready for merging. 

Change summary: I have seized the opportunity to write a better (in fact more correct...) treatment if 16bit in-code constants, which are sometimes signed, sometimes unsigned. This was a long-standing hidden bug.

I also followed the now standard implementation of the return instruction  (here `jr $31`): with `-variant telechat`, exit; without jump to register contents.

**Comment by lukeg101** [comment]
Thank you very much Luc, and apologies for my slow reply! lot's of work in the pipeline right now!

**Pull request merged**
