### PR TITLE
[herd] fix tagloc initialisation for labels

### PR DESCRIPTION
**Pull request by artkhyzha**
This PR aims to resolve an issue arising with `-variant memtag`: whenever a register contains a label, herd7 creates an initial write for the instruction at that label, which the MTE variant then attempts to assign an initial tag to -- leading to an crash. For instance, consider the following minimal litmus test:
```
AArch64 AK001
{}
P0        ;
ADR X0,L0 ;
L0:       ;
 NOP      ;
```
Before this PR it used to crash with an error:
```
herd7 -cat aarch64.cat  -variant memtag AK001.litmus
Warning: File "AK001.litmus": Illegal tagloc on 0:L0 (User error)
```

To resolve the problem, I suggest to simply disable creation of initial tags for initial writes to labels.

### CODE REVIEW

**Comment by artkhyzha** [comment]
Note that an alternative simple fix would be to guard creation of initial writes for instructions with a check for `-variant ifetch`. However, doing so in `mem.ml` (at line 387) would result in quite a few AArch64 tests failing. At least, my naive attempt led to:
```
Failed ./herd/tests/instructions/AArch64/A248.litmus : Missing file ./herd/tests/instructions/AArch64/A248.litmus.expected-failure
Failed ./herd/tests/instructions/AArch64/A251.litmus : Missing file ./herd/tests/instructions/AArch64/A251.litmus.expected-failure
Failed ./herd/tests/instructions/AArch64/L050.litmus : Missing file ./herd/tests/instructions/AArch64/L050.litmus.expected-failure
Failed ./herd/tests/instructions/AArch64/L051.litmus : Missing file ./herd/tests/instructions/AArch64/L051.litmus.expected-failure
Failed ./herd/tests/instructions/AArch64/L062.litmus : Missing file ./herd/tests/instructions/AArch64/L062.litmus.expected-failure
```

Hence, suggesting the commited fix.

**Comment by artkhyzha** [comment]
P.S. @relokin, I thought it might be good to ping you on the subject of this tiny change, because in a way it is about the interaction between ifetch and mte functionality in herd.

**Comment by artkhyzha** [comment]
Hi @relokin and @maranget -- just a quick check in case if perhaps this could be merged.

**Comment by relokin** [comment]
@maranget sorry to bother you with this PR once again, but it's a fairly small change and fixes a bug, do you think we can merge it?

**Comment by jalglave** [comment]
Go for it Nikos.
Thanks,
Jade

On 6 Oct 2023, at 23:50, Nikos Nikoleris ***@***.***> wrote:

﻿

⚠ Caution: External sender


@maranget<https://github.com/maranget> sorry to bother you with this PR once again, but it's a fairly small change and fixes a bug, do you think we can merge it?

**Comment by relokin** [comment]
Thanks @jalglave! I'm doing some more testing now and I will merge this by the end of today unless there are any objections.

**Comment by relokin** [comment]
Merged. Thanks @artkhyzha

**Comment by artkhyzha** [comment]
Thank you for the review!

**Pull request merged**
