### PR TITLE
ASL and AArch64 on ASL

### PR DESCRIPTION
**Pull request by HadrienRenaud**
This PR introduces:
 - a new language base in `lib` for ASL
 - a new arch for `herd` for executing ASL litmus tests
 - a new variant for `AArch64` that tells it to use ASL internally.

Open questions/TODO:

- [x] Is `iseq` in `herd/eventsMonad.ml` really needed? Since e4a67c850a49400ba6a678e76b4e8f24b3eb6052 every ASL event has a unique poi.
- [x] Can I factor things between `AArch64` and `AArch64ASL` in `herd/parseTest.ml`?
- [x] Can the variant `ASL` be replaced by an arch-specific feature or `dodep`/`catdep`? The variant is used [in `mem`](#diff-a412e5fcef461da4bedcf938096e834fbd0b53001e5104b5e9c2c5fea28f97eeR948) with `dodeps` and [in `machModelChecker`](#diff-14b855e0e67143bc2a00ef419b463f362f702c34f22ae3ca7a930f1521047d57R222) with `dodep` and `catdep`.
- [x] Is `herd/AArch64ASLArch_herd.ml` really needed?
- [x] How to deal with the `asllib` dependency?
- [x] Licenses
- [x] Check that it passes the tests

### CODE REVIEW

**Comment by HadrienRenaud** [comment]
- [x] Can I factor things between `AArch64` and `AArch64ASL` in `herd/parseTest.ml`?

Probably. Since ed4cdfd028ba42da27034582019fd2a1b0259187, the arch `AArch64ASL` has been replaced by `AArch64` with the variant `asl`. However, I did not manage to unify the two cases, as it would require me to unify the types of `AArch64Sem.ml` and `AArch64ASLSem.ml` without editing `AArch64Sem.ml` so I will keep it as it is until further notice.

**Comment by HadrienRenaud** [comment]
- [x] Can the variant ASL be replaced by an arch-specific feature or dodep/catdep? The variant is used [in mem](https://github.com/herd/herdtools7/pull/462#diff-a412e5fcef461da4bedcf938096e834fbd0b53001e5104b5e9c2c5fea28f97eeR948) with dodeps and [in machModelChecker](https://github.com/herd/herdtools7/pull/462#diff-14b855e0e67143bc2a00ef419b463f362f702c34f22ae3ca7a930f1521047d57R222) with dodep and catdep.

Probably not. Using `catdep` and `dodep` have deep intricated consequences that I do not want to have to deal with.

**Comment by HadrienRenaud** [comment]
After ffff88b4080d87412649364d8431c373155ea108 it passes the tests ([cf this pastebin](https://privatebin.net/?1fd290237f5b7ca0#BBURrG5FtWGUJjoNUxGHkEaZTT3tuB8KqoqYWjpe8CQb))

**Comment by HadrienRenaud** [comment]
@maranget do we need to change `dune-workspace.versions` to confirm the drop of compatibility for Ocaml prior to 4.08.01?

**Comment by maranget** [comment]
> @maranget do we need to change `dune-workspace.versions` to confirm the drop of compatibility for Ocaml prior to 4.08.01?

We do. And we need to check :)

**Comment by maranget** [comment]
Hi @HadrienRenaud. I have merged PR #462, nice work. 

 I managed to factor things between `AArch64` and `AArch64ASL` in `herd/parseTest.ml`. I also have included you extra commit 5d6e6014.

Because of this I suggest that you go on from a fresh fork from master

**Comment by HadrienRenaud** [comment]
Great thank you! 🎉

**Pull request merged**
