### PR TITLE
[action] Periodic check www build

### PR DESCRIPTION
**Pull request by maranget**
In practice a periodic adaptation of build-www, with no output artifact. See also PR #821.

### CODE REVIEW

**Comment by maranget** [comment]
Hi @relokin. Here is an attempt at a weekly check of www build. I have checked what happens in case of failure:  I received an email. I guess I received teh email as the last to modify the action file, as written in the doc. It would be nicer if the message could be sent to specified emails, but I found no simple way to do so.

**Comment by relokin** [comment]
Looks good to me, obviously the notification is still an issue.

There are ways to send emails to custom contacts but one would have to provide access to an SMTP server.

Another workaround would be add a [badge](https://github.com/OWNER/REPOSITORY/actions/workflows/WORKFLOW-FILE/badge.svg) to the README.md. Not as good as notifying everyone but at least there is an obvious sign that a test failed in the landing page of the repository.

**Comment by relokin** [comment]
> I have an idea. As I receive the emails as the last author of the action script, I can set an automatic forwarding of those emails. Would you be part of an experiment?

Yes happy to help!

**Comment by relokin** [comment]
I got an email about this!

**Comment by maranget** [comment]
Great, there is always a way... 

Thanks, please ignore my other message. 

--Luc

**Comment by maranget** [comment]
Great, maybe someone else would like to receive CI failure messages @jalglave, @HadrienRenaud?

**Comment by jalglave** [comment]
Yes please @maranget.

**Review by relokin — APPROVED** [review]

**Pull request merged**
