### PR TITLE
[herd] Fix NSH and add support for nXS TLBI instructions

### PR DESCRIPTION
**Pull request by relokin**
In the Armv8-A architecture, some TLBI variants (for example, TLBI VMALLE1) do not invalidate TLB entries of other cores/PEs (as opposed to TLBI VMALLE1IS). Make sure that for such variants the inv-domain relation does not relate TLBI events with external events.

### CODE REVIEW

**Comment by jalglave** [comment]
Thanks @relokin. Might you consider adding nXS to this PR? 
Jade

**Comment by relokin** [comment]
> Thanks @relokin. Please might you consider adding nXS to this PR? Jade

Hey Jade, the 2nd patch now adds support for nXS variants of the TLBI instruction.

**Comment by jalglave** [comment]
Excellent, thanks Nikos!
Jade

On 25 Sep 2023, at 17:56, Nikos Nikoleris ***@***.***> wrote:

﻿

⚠ Caution: External sender


Thanks @relokin<https://github.com/relokin>. Please might you consider adding nXS to this PR? Jade

Hey Jade, the 2nd patch now adds support for nXS variants of the TLBI instruction.

**Comment by jalglave** [comment]
this looks good to me - please can we merge? @maranget

**Comment by relokin** [comment]
I am converting this to draft, I think, there is a better way to implement TLBIs that apply to the local PE only - create a new 'NSH' set and then consider that set when we enumerate inv-domain in the cat file.

**Comment by relokin** [comment]
I think this PR is now ready.

**Comment by maranget** [comment]
Hi @relokin, `make aarch32-test` was no longer functional. The commit above intends to fix this. Starting a complete VMSA regression.

**Comment by relokin** [comment]
> Hi @relokin, `make aarch32-test` was no longer functional. The commit above intends to fix this. Starting a complete VMSA regression.

Thanks Luc, I wasn't aware that aarch32.cat includes aarch64.cat thanks for the fix!

**Comment by maranget** [comment]
You are welcome, now I feel useful :)

**Comment by maranget** [comment]
Hi @relokin, complete regression yields the two tests aforementioned and only those. Commit squashed and rebased, merging is imminent. Amy last minute objection?

**Comment by relokin** [comment]
Thanks Luc! No objections, let's merge :)

**Comment by maranget** [comment]
In the Armv8-A architecture, some TLBI variants (for example, TLBI VMALLE1) do not invalidate TLB entries of other cores/PEs (as opposed to TLBI VMALLE1IS). Make sure that for such variants the inv-domain relation does not relate TLBI events with external events.

This PR also  adds support for nXS variants of the TLBI instruction.

**Pull request merged**
