### PR TITLE
[herd] fix typos

### PR DESCRIPTION
**Pull request by DehengYang**

### CODE REVIEW

**Comment by DehengYang** [comment]
Dear All,

I am learning herd via debugging the herd project and reading its source code. During the process, I find a minor typo in the herd argument parser part, and thus I create this PR. Please kindly advise. 

Thank you in advance for your time and consideration.

Yours sincerely,
Deheng

**Comment by DehengYang** [comment]
Dear @maranget ,

I have found and fixed a set of typos throughout the process of diy documentation reading. I hope this PR could be helpful.

Yours sincerely,
Deheng

**Comment by maranget** [comment]
Hi @DehengYang, are you still chasing typos?

**Comment by DehengYang** [comment]
Dear @maranget ,

I have finished the typo fixing process, in which I tried my best to find typos and rectify them. 

Many thanks and wish you a great weekend!

Yours sincerely,
Deheng

**Comment by maranget** [comment]
Merged, thanks for your work @DehengYang.

**Pull request merged**
