### PR TITLE
[aarch64,sve] Add support for SVE EOR vectors, unpredicated

### PR DESCRIPTION
**Pull request by yuxiliu-arm**
Similar to `I_ADD_SV`, the SVE EOR instruction is added as `I_EOR_SV`. Tested with `diy7` on `qemu-aarch64`.

### CODE REVIEW

**Comment by yuxiliu-arm** [comment]
> Can you, please, squash `[aarch64,sve] Fix EOR to only allow D reg` into `[aarch64,sve] Add support for SVE EOR vectors, unpredicated`. Since it is new instruction let's start with the best possible implementation 😉

Done.

**Review by relokin — APPROVED** [review]
Code looks good to me, regressions run and the test with litmus runs as expected. Thanks @yuxiliu-arm!

I'll merge this before the end of today, unless I hear any objections.

**Comment by maranget** [comment]
> I'll merge this before the end of today, unless I hear any objections.

Hi @relokin  and @yuxiliu-arm. I am fine with merging. Several merges have been performed since the last push. So, for the sake of a nice, linear, history, it would be better to rebase on master before merging. Thanks.

**Comment by relokin** [comment]
I agree @maranget, @yuxiliu-arm can you please rebase your PR on master and then we can merge this.

**Comment by relokin** [comment]
Regressions passed and merged. Thanks @yuxiliu-arm

**Pull request merged**
