### PR TITLE
[herd] Avoid po relation between events of the same instance

### PR DESCRIPTION
**Pull request by relokin**
Signed-off-by: Nikos Nikoleris <nikos.nikoleris@arm.com>

### CODE REVIEW

**Comment by maranget** [comment]
Hi @relokin, for testing modifications of the internal check, it may be a good idea to disable candidate optimisation with option `-optace false`.

**Comment by maranget** [comment]
I have tested this PR on an enlarged test base, including the new tests of PR #456.

**Comment by relokin** [comment]
Many thanks for this @maranget!

Out of curiosity, I saw you added many tests as the regression. Do you think running these is enough? Or do you have more tests privately?

**Comment by maranget** [comment]
> Many thanks for this @maranget!
> 
> Out of curiosity, I saw you added many tests as the regression. Do you think running these is enough? Or do you have more tests privately?

Most of the tests are from a test based that we built in collaborations with the Cambridge University team. Those are the tests we routinely  on hardware, see [here](https://cambium.inria.fr/~maranget/cats7/model-aarch64/) for links to archives of those tests. I also have a few additional tests.

**Comment by maranget** [comment]
Thanks @relokin, merged.

**Pull request merged**
