### PR TITLE
Refactor monad

### PR DESCRIPTION
**Pull request by maranget**

### CODE REVIEW

**Comment by jalglave** [comment]
hi Luc, thank you so much for doing this. Please could you refactor even further, as follows.
At the moment you have:
```
(* A few monad constructors from action and instruction instance *)
     let mk_singleton_es a ii =
       make_one_event_structure a ii ++ make_one_monad () []

[...]

let make_one_event_structure_data is_data =
       if is_data then
         fun a ii -> make_one_event_structure a ii -- add_data_ports
       else 
         make_one_event_structure

[...]

(* Fresh variables are generated by reading *)
     let read_loc is_data mk_action loc ii = fun eiid ->
       (* It is important to call V.fresh_var
          for every _complete_ call of read_loc *)
       let v = V.fresh_var () in
       let m =
         make_one_event_structure_data is_data (mk_action loc v) ii ++
         make_one_monad v [] in
       m eiid

     (* Writing is as simple as emiting one event *)
     let write_loc mk_action loc ii =  mk_singleton_es (mk_action loc) ii
```

Please could you either inline the use of `mk_singleton_es` in `write_loc` or on the contrary factorise the following snippet in `read_loc`:

```
         make_one_event_structure_data is_data (mk_action loc v) ii ++
         make_one_monad v []
```
so that the functions `read_loc` and `write_loc` look more obviously closer in the bricks they use?
Thanks in advance,
Jade

**Comment by maranget** [comment]
Et voilà.

**Comment by jalglave** [comment]
Super thank you. Sorry for being a pain, but whilst we're at it, please can we rename a bunch of functions in AArch64Sem for consistency?
For example:
`do_read_mem` -> `read_mem_and_write_reg`
`old_do_read_mem` -> `do_read_mem`

and also there's a `do_str` but no `do_ldr` - the discrepancy looks a little odd to me.
Thanks,
Jade

**Comment by maranget** [comment]
Et voilou. I have to stop now. Notice that you can commit in branch yourself before merging, if there still are some possible improvements.

**Comment by jalglave** [comment]
Thanks Luc!
Jade

**Pull request merged**
