### PR TITLE
[herd] Variant declaration in test override other declarations.

### PR DESCRIPTION
**Pull request by maranget**
Variant are first defined by command line and configuration file.
Those global declarations are overridden by any test specific
declaration `Variant=...` from test source.

Some part of herd code (specifically the `Mem` module) was unaware
of such overriding.

### CODE REVIEW

**Comment by relokin** [comment]
Incidentally, I also run into the same issue in #405 https://github.com/herd/herdtools7/pull/405/commits/e7cb55d468255d632d9b325f48105df25abb33b9

**Comment by maranget** [comment]
> Incidentally, I also run into the same issue in #405 [e7cb55d](https://github.com/herd/herdtools7/commit/e7cb55d468255d632d9b325f48105df25abb33b9)

Ah! I see we have very similar solutions. I additionally extracted the `Make` out of the `Top` functor, as all references to `TopConf` have disappeared from `Make`. What should we do? BTW is your PR #405 ready for review?

**Comment by relokin** [comment]
Hey @maranget, up to you, let's go with the solution that is technically better (I am happy to get rid of my commit that is).

Yes #405 is ready for review.

**Comment by maranget** [comment]
Since #405 is ready, it looks easier to keep it as it is.

**Pull request closed without merging**
