### PR TITLE
Unify Dune & OCamlbuild built binaries

### PR DESCRIPTION
**Pull request by eth-arm**
Add dont7 to Dune, and mcat2includes7 to OCamlbuild.

### CODE REVIEW

**Comment by maranget** [comment]
Ethel,  having discussed with Jade, we agree to deprecate `dont`. It would be nice if you could change the PR accordingly.
Thanks.

**Comment by eth-arm** [comment]
I have removed the addition of `dont` to Dune from the first commit, and removed the `dont` binary itself in a second commit. It's still referenced in the documentation; should I also remove that?

**Comment by maranget** [comment]
> I have removed the addition of `dont` to Dune from the first commit, and removed the `dont` binary itself in a second commit. It's still referenced in the documentation; should I also remove that?

Thanks, yes please remove any reference to `dont` from the documentation.

**Comment by eth-arm** [comment]
I think I have removed `dont`/`auto` from the codebase.

**Pull request merged**
