### PR TITLE
[all]: Added movk to AArch64

### PR DESCRIPTION
**Pull request by lukeg101**
This patch upstreams support for the movk instruction in AArch64.
This has similar semantics to movz, but shifting in a 16 bit immediate
and keeping all over bits untouched.

Unittests are provided as needed

Following https://github.com/herd/herdtools7/pull/31

### CODE REVIEW

**Comment by lukeg101** [comment]
- Rebased onto newest commit
- Added unittests .expected files
- Ran pre-commit checks  - passed
- Ran make test - passed

**Comment by jalglave** [comment]
hi @lukeg101  sorry please could you have a look at the conflict in lib/AArch64Base? then I'll integrate it.
Thanks,
Jade

**Comment by lukeg101** [comment]
- rebased and renamed tests

**Comment by jalglave** [comment]
Thanks Luke!
Jade

**Pull request merged**
